version: '3'
services:
  demo-web:
    build: .
    platform: linux/amd64
    command: "./bin/rails server -b '0.0.0.0'"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rails/storage
    ports:
      - "3000:3000"
  nginx:
    build: ./nginx
    platform: linux/amd64
    container_name: nginx_container
    depends_on:
      - demo-web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  postgres_data: {}
  app-storage: {}